### ISSUE TITLE
Robinhood - csv Error

### ISSUE THREAD

**Issue by combatdoc7id** [joshfraser/robinhood-to-csv#33] opened 2018-09-30 23:53 UTC
I am receiving this error when running the bat file

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cdesai-qi** [comment] 2018-10-06 07:43
Duplicate of #29

**Comment by joshfraser** [comment] 2018-12-27 07:11
Should be fixed with #36. Feel free to reopen if that's not the case.

**Closed by joshfraser** 2018-12-27 07:11 UTC
