### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by murdrae** [joshfraser/robinhood-to-csv#32] opened 2018-09-26 22:48 UTC
Python 3.6.5 on OSX 10.13.6
After entering username and password getting error:
Traceback (most recent call last):
  File "csv-options-export.py", line 45, in <module>
    logged_in = robinhood.login(username=username, password=password)
  File "/Users/jason/Documents/repo/RS/robinhood-to-csv/Robinhood.py", line 81, in login
    res = res.json()
  File "/Users/jason/Documents/repo/RS/robinhood-to-csv/env/lib/python3.6/site-packages/requests/models.py", line 896, in json
    return complexjson.loads(self.text, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0

**Comment by vignesh57** [comment] 2018-09-30 06:12
Python 3.6 on windows 10. Experiencing this exact same error when trying to export using csv-export.py.

**Comment by cdesai-qi** [comment] 2018-10-06 07:45
Duplicate of #29 
See the solution posted in pull request #30

**Comment by joshfraser** [comment] 2018-12-27 07:12
Should be fixed with #36. Feel free to reopen if that's not the case.

**Closed by joshfraser** 2018-12-27 07:12 UTC
